/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 5.8 */
/* Fri Mar 12 11:17:48 2021 */

/* parameterized module instance */
i2s_rx_fifo __ (.Data( ), .WrClock( ), .RdClock( ), .WrEn( ), .RdEn( ), 
    .Reset( ), .RPReset( ), .Q( ), .WCNT( ), .RCNT( ), .Empty( ), 
    .Full( ), .AlmostEmpty( ));
