/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 7.5 */
/* Mon Feb 15 11:42:42 2021 */

/* parameterized module instance */
line_uv_bram __ (.Clock( ), .ClockEn( ), .Reset( ), .WE( ), .Address( ), 
    .Data( ), .Q( ));
