//=============================================================================
// Verilog module generated by IPExpress
// Filename: ddr3_ip_inst_inst.v
// Copyright(c) 2013 Lattice Semiconductor Corporation. All rights reserved.   
//=============================================================================

//------------------------------------------------
// Username module instantiation template
//------------------------------------------------

ddr3_ip_inst U1_ddr3_ip_inst (

   // Clock and reset
   .eclk               (eclk),
   .sclk               (sclk),
   .rst_n              (rst_n),
   .mem_rst_n          (mem_rst_n),

   // Input signals from the User I/F  
   .init_start         (init_start),  
   .cmd                (cmd),
   .addr               (addr),
   .cmd_burst_cnt      (cmd_burst_cnt),
   .cmd_valid          (cmd_valid),   
   .ofly_burst_len     (ofly_burst_len), 
   .write_data         (write_data),
   .data_mask          (data_mask),
   .ddr_rst            (ddr_rst),
   .dqsdel             (dqsdel),
   .dqsbuf_pause       (dqsbuf_pause),
   .clocking_good      (clocking_good),
   .update_done        (update_done),

   // Output signals to the User I/F
   .cmd_rdy            (cmd_rdy),
   .datain_rdy         (datain_rdy),
   .init_done          (init_done),
   .rt_err             (rt_err),
   .wl_err             (wl_err),
   .read_data          (read_data),
   .read_data_valid    (read_data_valid),
   .dll_update         (dll_update),
   // Memory side signals 
   .em_ddr_reset_n     (em_ddr_reset_n),
   .em_ddr_data        (em_ddr_data),
   .em_ddr_dqs         (em_ddr_dqs),
   .em_ddr_clk         (em_ddr_clk),
   .em_ddr_cke         (em_ddr_cke),
   .em_ddr_ras_n       (em_ddr_ras_n),
   .em_ddr_cas_n       (em_ddr_cas_n),
   .em_ddr_we_n        (em_ddr_we_n),
   .em_ddr_cs_n        (em_ddr_cs_n),
   .em_ddr_odt         (em_ddr_odt),
   .em_ddr_dm          (em_ddr_dm),           
   .em_ddr_ba          (em_ddr_ba),
   .em_ddr_addr        (em_ddr_addr)
);


