// ===========================================================================
// Verilog module generated by IPexpress
// Filename: ddr3_sdram_mem_top.v  
// Copyright 2011 (c) Lattice Semiconductor Corporation. All rights reserved.
// ===========================================================================

`timescale 1ns/100ps

module ddr3_ip_inst (

   // Clock and reset
   eclk,
   sclk,
   rst_n,
   mem_rst_n,

   // Input signals from the User I/F  
   init_start,  
   cmd,
   addr,
   cmd_burst_cnt,
   cmd_valid,   
   ofly_burst_len, 
   write_data,
   datain_rdy,
   data_mask,
   ddr_rst,
   dqsdel,
   dqsbuf_pause,
   clocking_good,
   update_done,


   // Output signals to the User I/F
   cmd_rdy,
   init_done,
   rt_err,  
   wl_err,  
   read_data,
   read_data_valid,
   dll_update,

   // Memory side signals 
   em_ddr_reset_n,          
   em_ddr_data,
   em_ddr_dqs,
   em_ddr_clk,
   em_ddr_cke,
   em_ddr_ras_n,
   em_ddr_cas_n,
   em_ddr_we_n,
   em_ddr_cs_n,
   em_ddr_odt,
   em_ddr_dm,           
   em_ddr_ba,
   em_ddr_addr
)/* synthesis syn_black_box black_box_pad_pin="em_ddr_data[15:0],em_ddr_dqs[1:0],em_ddr_dm[1:0],em_ddr_clk[0:0],em_ddr_odt[0:0],em_ddr_cke[0:0],em_ddr_cs_n[0:0],em_ddr_addr[26:0],em_ddr_ba[2:0],em_ddr_ras_n,em_ddr_cas_n,em_ddr_we_n" */;

// ====================================================================
// Port definition 
// ====================================================================
input                            eclk;
input                            sclk;
input                            rst_n;
input                            mem_rst_n;

// Input signals from the User I/F
input                            init_start; 
input   [3:0]                    cmd;
input   [26:0]                   addr;
input   [4:0]                    cmd_burst_cnt;
input                            cmd_valid;
input                            ofly_burst_len;

input   [63:0]                  write_data;
input   [7:0]                   data_mask;
input                            ddr_rst;
input   [1:0]                 dqsdel;
input                            dqsbuf_pause;
input                            clocking_good;
input                            update_done;

output  [63:0]                  read_data /* synthesis syn_useioff = 0 */;

output                           datain_rdy;


// Output signals to the User I/F
output                           cmd_rdy;
output                           init_done;
output                           rt_err;  
output                           wl_err;  
output                           read_data_valid  /* synthesis syn_useioff = 0 */;

output                           dll_update;

// Memory side signals 
inout   [15:0]                   em_ddr_data;
output                           em_ddr_reset_n;
inout   [1:0]                    em_ddr_dqs;
output  [1:0]                    em_ddr_dm;
output  [0:0]                    em_ddr_clk;
output  [0:0]                    em_ddr_cke;
output                           em_ddr_ras_n;
output                           em_ddr_cas_n;
output                           em_ddr_we_n;
output  [0:0]                    em_ddr_cs_n;
output  [0:0]                    em_ddr_odt;
output  [13:0]                   em_ddr_addr;
output  [2:0]                    em_ddr_ba;


endmodule
