/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 5.8 */
/* Tue Jan 12 21:20:15 2021 */

/* parameterized module instance */
ddr_in __ (.clkin( ), .reset( ), .sclk( ), .datain( ), .q( ));
